### ISSUE TITLE
GenerateLicensePage doenst work

### ISSUE THREAD

**Issue by rviannaoliveira** [cookpad/license-tools-plugin#105]
Hey guys,
I have two problems.

First, I created the file `licenses.yml` and run the command  `updateLicense` but when I generated with the 
`./gradlew generateLicensePage` appeared this error:

```
> Not enough information for:
  - artifact: com.google.firebase:firebase-messaging:17.0.0
    name: firebase-messaging
    copyrightHolder: #AUTHOR# (or authors: [...])
    year: #YEAR# (optional)
  - artifact: org.apache.ant:ant:1.8.0
    name: org.apache.tools.ant
    license: #LICENSE#
    copyrightHolder: #AUTHOR# (or authors: [...])
    year: #YEAR# (optional)
  - artifact: com.android.support:transition:28.0.0
    name: Android Transition Support Library
    copyrightHolder: #AUTHOR# (or authors: [...])
    year: #YEAR# (optional)
  - artifact: org.robolectric:robolectric:3.0
    name: robolectric
    license: #LICENSE#
    copyrightHolder: #AUTHOR# (or authors: [...])
    year: #YEAR# (optional)
  - artifact: org.altbeacon:android-beacon-library:2.12.3
    name: android-beacon-library
    copyrightHolder: #AUTHOR# (or authors: [...])
    year: #YEAR# (optional)
  - artifact: javax.annotation:jsr250-api:1.0
    name: JSR-250 Common Annotations for the JavaTM Platform
    copyrightHolder: #AUTHOR# (or authors: [...])
    year: #YEAR# (optional)
  - artifact: com.firebase:firebase-jobdispatcher:0.8.5
    name: firebase-jobdispatcher
    copyrightHolder: #AUTHOR# (or authors: [...])
    year: #YEAR# (optional)
```

When I substitute the `#AUTHOR`  to something and after I execute the command  the second problem appear:

> java.io.FileNotFoundException: File not found: template/licenses/Android Software Development Kit License.html

**Comment by hetang** [comment]
any update on this issue. I am also facing same.

**Comment by Pooja-Bhavsar** [comment]
Any update on this issue?? Facing the same.

**Comment by astamato** [comment]
Same issue :(

**Comment by ochim** [comment]
私も同じ問題に直面しています。
Android Software Development Kit Licenseは[これ](https://developer.android.com/studio/terms.html)なのですが。
skip: true するしかないでしょうか？

**Comment by saurabhmdh** [comment]
i am also having same issue due to this issue unable to generate html file on assets folder,

**Comment by vivekwolf123** [comment]
Any update on this? I have the same issue - java.io.FileNotFoundException: File not found: template/licenses/Android Software Development Kit License.html

**Comment by k4zy** [comment]
We are going to archive this repository.  
Please migrate https://github.com/kazyApp/LicenseToolsPlugin  
We already resolved this problem.  (Supported Android Software Development Kit License)
Thanks
