### ISSUE TITLE
license-tools-plugin v2.0

### ISSUE THREAD

**Issue by litmon** [cookpad/license-tools-plugin#106]
The maintenance cost increased because License Templates must have this plugin. (Operation for adding Templates is not prepared.)

So I propose main feature for v2.0.0 that plugin generate html only showing License Page URL.
In the future, we don't need maintain License Templates.

**Comment by k4zy** [comment]
v2.0 is here https://github.com/kazyApp/LicenseToolsPlugin
I have some ideas for template management issue.
