### ISSUE TITLE
updateLicense should remove licenses of unused dependecies

### ISSUE THREAD

**Issue by rallat** [cookpad/license-tools-plugin#107]
There checkLicense is failing because of unused licenses in the yml
```> Task :app:checkLicenses FAILED
# Libraries listed in /Users/ifc/mercari/mercari-android/app/licenses.yml but not in dependencies:
- artifact: xmlpull:xmlpull:+

- artifact: com.thoughtworks.xstream:xstream:+

- artifact: xpp3:xpp3_min:+
```
I would expect from the `updateLicense` task to remove then but it doesn't.

**Comment by iamutkarshtiwari** [comment]
@litmon 🙏

**Comment by iamutkarshtiwari** [comment]
My idea to solve this is by re-writing the whole `licenses.yml` every time we call 
`./gradlew updateLicences`. This way we can make sure that we don't add any unused licenses.

What do you think about this approach? @nein37 @litmon

**Comment by k4zy** [comment]
We are going to archive this repository.  
Please migrate https://github.com/kazyApp/LicenseToolsPlugin  
This problem maybe resolved.
