### ISSUE TITLE
Cannot show OSS version in report.

### ISSUE THREAD

**Issue by jyyoung89** [cookpad/license-tools-plugin#118]
The report that generates using 'generateLicences' task could not show the OSS version, only showing wildcard.
So it would be a good idea to add configuration options to select either the OSS version or the wildcard version.
If you know the solution to show OSS version, please let me know.

Thanks.

**Comment by k4zy** [comment]
Thanks for creating issue!
Unfortunately There is no solution.
Please tell us that why you show OSS version in report.
If you have yet motivation, create issue https://github.com/kazyApp/LicenseToolsPlugin
