### ISSUE TITLE
how to add the license info for our own library modules?

### ISSUE THREAD

**Issue by samlu** [cookpad/license-tools-plugin#120]
Here is an example of my projects.
ProjA - app, LibComm, libA, exlibA.aar
ProjB - app, LibComm, LibB, exlibB.aar
ProjC - app, LibComm, LibC, exlibA.aar

The LibComm is an Android library module (https://developer.android.com/studio/projects/android-library) and will be used by ProjA, ProjB, ProjC, etc. This library also uses some open source files (directly include the source files, not use .aar or .jar). Currently, this license plug-in won't list the license information of LibComm in the liceses.yaml file as it has no idea where the license information is.

Is there a way for us to specify the license information for LibComm (I don't prefer the .pom scheme for this as we won't public LibComm to remote/local Marven) so we don't have to manually edit the licenses.yaml file of each project that uses LibComm?

Thank you for creating this awesome license plugin.

**Comment by k4zy** [comment]
This plugin does not support private package.
Thanks
