### ISSUE TITLE
the generated licenses.json file is not encoded in UTF-8

### ISSUE THREAD

**Issue by samlu** [cookpad/license-tools-plugin#121]
I found the generated licenses.json file is not encoded in UTF-8.
Please add 'UTF-8' when calling File.write()

```
void generateLicenseJson(Project project) {
  ...
  // project.file("${assetsDir}/${ext.outputJson}").write(json.toString())
  // should be changed as
  project.file("${assetsDir}/${ext.outputJson}").write(json.toString(), 'UTF-8')
}
```

**Comment by k4zy** [comment]
We are going to archive this repository.
Please migrate https://github.com/kazyApp/LicenseToolsPlugin
We already resolved this problem.
Thanks
