### ISSUE TITLE
File not found Exception

### ISSUE THREAD

**Issue by interkenny** [cookpad/license-tools-plugin#122]
> java.io.FileNotFoundException: File not found: template/licenses/Android Software Development Kit License.html
>> java.io.FileNotFoundException: File not found: template/licenses/Crashlytics Terms of Service.html

like #113 #114 

@iamutkarshtiwari 
Is it possible to add these to the template. Thanks.

**Comment by k4zy** [comment]
We are going to archive this repository.  
Please migrate https://github.com/kazyApp/LicenseToolsPlugin  
I am now trying to this problem. kazyApp/LicenseToolsPlugin#1
