### ISSUE TITLE
Allow wildcards for elements of the dependency group

### ISSUE THREAD

**Issue by MarcelBochtler** [cookpad/license-tools-plugin#126]
AndroidX dependencies use the naming schema `androidx.<component>:<component>:<version>`.
E.g. `androidx.appcompat:appcompat:1.1.0` or `androidx.arch.core:core-runtime:2.1.0`

When using this plugin every androidx component needs to be declared separately.
It might be a good addition to support wildcards like:
`androidx.appcompat:appcompat:1.1.0` --> `androidx.+:+:+`
or even
`androidx.*:+:+` --> `androidx.arch.core:core-runtime:2.1.0`

It would already be a big improvement if only the last component of the group can be used with a wildcard

**Comment by k4zy** [comment]
Thanks for your good suggestion. but We have no plan to aggregate library infomation.
