### ISSUE TITLE
Use ch.netzwerg.release plugin

### ISSUE THREAD

**Issue by netzwerg** [cookpad/license-tools-plugin#19]
Just a heads-up: I am the developer of [ch.netzwerg.release](https://github.com/netzwerg/gradle-release-plugin), a plugin which provides all your `bumpMajor`, `bumpMinor`, `bumpPatch` and `releng` out of the box. It would be easy to use it in your build and I would be happy to assist if you need help!

Cheers, Rahel

**Comment by gfx** [comment]
Thanks to the information. Will try it 😂

**Comment by k4zy** [comment]
Thanks for the information
