### ISSUE TITLE
generateLicencePage complains about missing license template

### ISSUE THREAD

**Issue by wmontwe** [cookpad/license-tools-plugin#21]
When I execute `generateLicensePage`, it fails with missing template for `template/licenses/Answers Terms of Service.html`. Is there a way to provide this template?

My setup:

build.gradle:

```
dependencies {
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
}
```

licenses.yml

```
- artifact: com.crashlytics.sdk.android:answers:+
  name: Android SDK Answers
  copyrightHolder: Crashlytics, Inc.
  license: Answers Terms of Service
```

**Comment by gfx** [comment]
I think it is not open sourced. Add `skip: true` for non-OSS libraries.
