### ISSUE TITLE
License url

### ISSUE THREAD

**Issue by knordbo** [cookpad/license-tools-plugin#27]
It would be nice if the license url could be a part of the .yml and .json generated file (and potentially the .html output, but less likely needed there). It's already available in the pom file, so we can get it at best effort.

I'll put up a PR for this.

**Comment by komatatsu** [comment]
What’s the benefit if we know the url ?

**Comment by knordbo** [comment]
@komatatsu it means you can link to the license file without hosting it locally. crashlytics, fabric and other dependencies use PDF-files etc. for their licenses and its too heavy to store locally in an android app.

**Comment by komatatsu** [comment]
Thanks for your comment. I also checked pom.html, https://maven.apache.org/pom.html#Licenses, and found the attribute. I’ll release new version after merge the PR.

**Comment by knordbo** [comment]
Cheers!

**Comment by komatatsu** [comment]
v0.18.0 release
