### ISSUE TITLE
Warning shown in Gradle 3.0

### ISSUE THREAD

**Issue by hkurokawa** [cookpad/license-tools-plugin#34]
I found a warning is shown when I run `./gradlew tasks` as below. The indicated line is where I call `apply plugin: 'com.cookpad.android.licensetools'`. When I remove the line, the warning has gone.

```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_cxnzy1oizz1xepnt3c2kgftri.run(/Users/hiroshi/workspaces/sample-app/app/build.gradle:15)
```

My Gradle version is like below:

```
------------------------------------------------------------
Gradle 3.2.1
------------------------------------------------------------

Build time:   2016-11-22 15:19:54 UTC
Revision:     83b485b914fd4f335ad0e66af9d14aad458d2cc5

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_77 (Oracle Corporation 25.77-b03)
OS:           Mac OS X 10.11.6 x86_64
```

I am wondering a code like below might cause this warning as it is deprecated. See http://mrhaki.blogspot.jp/2016/11/gradle-goodness-replacing-operator-for.html for more details.

```groovy
25        def checkLicenses = project.task('checkLicenses') << {
```

[LicenseToolsPlugin.groovy#L25](https://github.com/cookpad/license-tools-plugin/blob/e1fd07d9de9adc18af73de0cc3b6fb43705b4ff2/plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy#L25
)

Probably, the solution would be just replacing `<<` with `doLast`, which is suggested in a warning message.

Thanks.

**Comment by ikesyo** [comment]
I've submitted #35 to address this.
