### ISSUE TITLE
CC0 Support

### ISSUE THREAD

**Issue by hkurokawa** [cookpad/license-tools-plugin#38]
I would like to include RxJava 2 in my app. Though the library itself is licensed by Apache License, its dependency, Reactive Streams (https://github.com/reactive-streams/reactive-streams-jvm) seems licensed by CC0, [Creative Commons 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/legalcode).

Currently, license-tools-plugin don't recognise such license type. So I am wondering if I could add the template to the tool so that it could support CC0.

Let me know your thoughts. I am not sure if we should remark CC0. Plus, I do not know which license should I include (Probably https://creativecommons.org/publicdomain/zero/1.0/legalcode itself?).

Thank you for your support in advance.

**Comment by uzzu** [comment]
Sorry for late response. 
I took legal confirmation, CC0 1.0 special credit notation is unnecessary. 
However, since I understand that it wanted for some developers as a stance, I will approve it features.  #45

**Comment by uzzu** [comment]
v0.23.0, containing CC0 support was released :)
