### ISSUE TITLE
Missing facebook license template

### ISSUE THREAD

**Issue by ndurell** [cookpad/license-tools-plugin#40]
I have the following entry in my licenses.yml:

```
- artifact: com.facebook.android:facebook-android-sdk:+
  name: Facebook-Android-SDK
  copyrightHolder: Facebook
  license: Facebook Platform License
  licenseUrl: https://github.com/facebook/facebook-android-sdk/blob/master/LICENSE.txt
  url: https://github.com/facebook/facebook-android-sdk
```
If I don't skip this entry I get the following error:
`File not found: template/licenses/Facebook Platform License.html`

I think this happens because there is no template for this license.
Should I add one or is that a complicated process?

**Comment by koyama-kani-daisuki** [comment]
Facebook Platform License is supported by #40.
Please try to use v0.21.0. Thanks.
