### ISSUE TITLE
Not working with gradle plugin 3.0.0-alpha7 and implementation(":module") 

### ISSUE THREAD

**Issue by mtiidla** [cookpad/license-tools-plugin#58]
We want to use the new `implementation()` and `api()` gradle apis that are available in gradle plugin 3.0.0. https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html

Unfortunately this raises the following errors:
```Execution failed for task ':example:checkLicenses'.
> Could not resolve all dependencies for configuration ':example:implementationCopy'.
   > Could not resolve project :example-dep.
     Required by:
         project :example
      > Cannot choose between the following configurations of project :example-dep:
          - debugApiElements
          - debugRuntimeElements
          - releaseApiElements
          - releaseRuntimeElements
        All of them match the consumer attributes:
          - Configuration 'debugApiElements':
              - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
              - Found org.gradle.api.attributes.Usage 'for compile' but wasn't required.
          - Configuration 'debugRuntimeElements':
              - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
              - Found org.gradle.api.attributes.Usage 'for runtime' but wasn't required.
          - Configuration 'releaseApiElements':
              - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
              - Found org.gradle.api.attributes.Usage 'for compile' but wasn't required.
          - Configuration 'releaseRuntimeElements':
              - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
              - Found org.gradle.api.attributes.Usage 'for runtime' but wasn't required.
```

I guess it is related to: 

> Plugin  3.0.0 includes a new dependency mechanism that automatically matches variants when consuming a library. This means an app's debug variant automatically consumes a library's debug variant, and so on.

See the changes required in the license plugin and example to run into this issue.
https://github.com/cookpad/license-tools-plugin/compare/master...mtiidla:gradle3_a7?expand=1

**Comment by ghost** [comment]
thanks!
We checked the reproducibility, but we struggle with resolving it..

**Comment by ghost** [comment]
`org.gradle.api.artifacts.ResolveException` is raised when `resolvedArtifacts` is called in https://github.com/cookpad/license-tools-plugin/blob/20967f0fbc70188e42489f550f7632fc0e5e3798/plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy#L294


If we catch the exception and ignore it, around https://github.com/cookpad/license-tools-plugin/blob/20967f0fbc70188e42489f550f7632fc0e5e3798/plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy#L29 will break...

hm..

**Comment by knordbo** [comment]
Is there any known workaround for this issue? It's a blocker for moving to gradle plugin 3.0.0 which is in beta 2 now.

**Comment by ghost** [comment]
📝 

https://stackoverflow.com/questions/45679847/android-studio-3-0-compile-issue-cannot-choose-between-configurations

We can prevent `Cannot choose between the following configurations of project :example-dep:` error with `configuration: 'default'`. But dependencies in the project can't be resolved.

**Comment by ghost** [comment]
Sorry for late fixing.

As I mentioned in https://github.com/cookpad/license-tools-plugin/issues/58#issuecomment-342127340 , the error is gradle issue and I've added the workaround in [readme](https://github.com/cookpad/license-tools-plugin#for-gradle-plugin-3-users).
And I also have merged to get all subproject's dependencies.
