### ISSUE TITLE
Support local jar libraries

### ISSUE THREAD

**Issue by uzzu** [cookpad/license-tools-plugin#63]
#56 from @rockwillj , supported local jar libraries.
Then I partially reverted it, because the `:checkLicense` task should not success when missing license. #62 

Implement local jar libraries support in other ways.

**Comment by uzzu** [comment]
Is there any problem in the following case?

1. `licenses.yml` separates for local jar libraries. (e.g. I name `licenses_local.yml`)
2. Library user write about origin library's license into `licenses.yml`, and write `skip: true`.
3. Library user write about local library's license into `licenses_local.yml`.
4. On `:generateLicense` task, refer dependency set from `licenses_local.yml` and merge into dependency set from `licenses.yml`.

I thought that can not consider the ordering description of licenses for local libraries, but I don't worry about it. :sweet_potato:

**Comment by k4zy** [comment]
Unfortunately We closed this issue, because there is no discussing for a long while. If you yet have motivations. Please re-create issue to https://github.com/kazyApp/LicenseToolsPlugin/issues/new
