### ISSUE TITLE
Android App with 2 Libraries (as part of the project)

### ISSUE THREAD

**Issue by DaRolla** [cookpad/license-tools-plugin#67]
Hi there,

I want to check the lib with my current app, which contains of one app module and two library modules.

I added the apply plugin: 'com.cookpad.android.licensetools' to the app build script (and later on to both library modules).

But it still breaks that it cannot find the licenses for the libraries.

Best regards,
DaRolla

**Comment by DaRolla** [comment]
Solved this using "ignoredGroups = ['the group name']

**Comment by ghost** [comment]
close because of https://github.com/cookpad/license-tools-plugin/issues/67#issuecomment-339607502

thanks!
