### ISSUE TITLE
How to handle unusual licenses ?

### ISSUE THREAD

**Issue by DaRolla** [cookpad/license-tools-plugin#68]
Hi there,

so the 'gradlew checkLicenses' generated this licenses.yml:

    - artifact: com.crashlytics.sdk.android:crashlytics:+
      name: Android SDK Crashlytics
      copyrightHolder: Google, Inc
      license: Crashlytics Terms of Service
      licenseUrl: http://try.crashlytics.com/terms/terms-of-service.pdf

But 'gradlew generateLicensePage' throws an error:

    Execution failed for task ':app:generateLicensePage'.
    > java.io.FileNotFoundException: File not found: template/licenses/Crashlytics Terms of Service.html

Simply removing the line 'license: Crashlytics Terms of Service' didn't help.

Can you please help me?

Cheers,
DaRolla

**Comment by DaRolla** [comment]
Solved this using "ignoredGroups = ['the group name']

**Comment by litmon** [comment]
Give `skip` field for specify artifact.

```
- artifact: com.crashlytics.sdk.android:crashlytics:+
  skip: true
```

https://github.com/cookpad/license-tools-plugin#optional-fields

**Comment by DaRolla** [comment]
but I need to name the open source software I used so skipping isn't an option

**Comment by skrzyneckik** [comment]
@DaRolla you can fork license-tools-plugin and add it manually as I did [here](https://github.com/skrzyneckik/license-tools-plugin) - check out feature/custom-license branch as well as [this commit](https://github.com/skrzyneckik/license-tools-plugin/commit/4618f9b9ff082e78039051aa392da62ddacfa350)

**Comment by janb4m** [comment]
this is a valid solution, but it would be great if we could have a config file or something that would allow us to add extra licenses

**Comment by k4zy** [comment]
We are going to archive this repository.
Please migrate https://github.com/kazyApp/LicenseToolsPlugin
I am now trying to this problem.
