### ISSUE TITLE
Wrap html links in licenses.html css

### ISSUE THREAD

**Issue by gabribela** [cookpad/license-tools-plugin#74]
Hi there,

the html links in the licenses.html are not wrapped if they are too long. So, the webview with the licenses in the android app is scrollable horizontally, which does not look so nice.
It would be great, if the links are wrapped and that the license.html file is only scrollable up and down and fit to the device screen.

Is it possible to add something like this in the css style?

 p {
    overflow-wrap: break-word;
}

That may solve the problem.

Thank you,

Gabriela

**Comment by zeh** [comment]
@gabribela Not exactly the most elegant solution, but I've solved this issue by adding a new task to `build.gradle` that injects new CSS (from a custom file) into `licenses.html` after it is generated.

```
task patchLicensePageStyles() {
    doLast {
        def additionalStylesFile = new File(project.rootDir, "app/src/main/assets/licensesAdditionalStyles.css")
        def licensesHTMLFile = new File(project.rootDir, "/app/src/main/assets/licenses.html")
        try {
            def additionalStyles = additionalStylesFile.getText('UTF-8')
            def licensesHTML = licensesHTMLFile.getText('UTF-8')
            licensesHTML = licensesHTML.replaceFirst(/(\s*<\/style>)/, "\n" + additionalStyles + "\$1")
            licensesHTMLFile.text = licensesHTML
        } catch(Exception e) {
            println e
        }
    }
}
generateLicensePage.finalizedBy(patchLicensePageStyles)
```

**Comment by k4zy** [comment]
Thanks for great suggetion and solution.
We are going to archive this repository.
Please migrate https://github.com/kazyApp/LicenseToolsPlugin
We will try this problem. https://github.com/kazyApp/LicenseToolsPlugin/issues/2
