### ISSUE TITLE
LicenseToolsPlugin requires all module dependencies (including not depends module's)

### ISSUE THREAD

**Issue by litmon** [cookpad/license-tools-plugin#91]
For example, the `example-no-dep` module create and add dependencies.
And **not** add to `example` module dependencies.

Then `./gradlew checkLicenses`, it failed to missing libraries in `example/licenses.yml`, but example does not have showing dependencies.

It caused by `project.rootProject.subprojects` in `resolveProjectDependencies` method.

https://github.com/cookpad/license-tools-plugin/blob/57e07ca20f316a35adb0872357e6cd0004aee9b6/plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy#L307

I think it is not intended behavior that all module's dependencies requires `example/licenses.yml`

**Comment by ellenhp** [comment]
A possible workaround for anyone who finds themselves needing one is to manually exclude modules with ignoredProjects like so: https://github.com/ellenpoe/aprs.tools/blob/27eebb3dff7cdaa78f5ebd9ee1677bd3042f3afb/mobile/build.gradle#L58

**Comment by k4zy** [comment]
We are going to archive this repository.  
Please migrate https://github.com/kazyApp/LicenseToolsPlugin  
This problem maybe resolved.
