### ISSUE TITLE
How to add additional Licenses

### ISSUE THREAD

**Issue by skauss** [cookpad/license-tools-plugin#95]
Dear all,
we use some content in our app which is a resource file (lottie animation which is a json file). (no Library, aar, jar , etc.)
The content has also a public license which I like to include in the license list.

Is there a way to add manually products with license to the output of  the licenseTools ?

Regards
Stephan

**Comment by k4zy** [comment]
We are going to archive this repository.
I am now trying to this problem. https://github.com/kazyApp/LicenseToolsPlugin/issues/1
